Improving the NN uisng NN module

**5 inputs - 1 output layer (1 neuron)**

In [12]:
# create the model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1) #wx+b num_features = x(input) and 1 = output neuron
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):  #forward propagation

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [14]:
# create the simple dataset
features = torch.rand(10,5)

# create the model instance
model = Model(features.shape[1])

# call the model for forward pass
# model.forward(features)
model(features)

tensor([[0.4141],
        [0.4457],
        [0.4087],
        [0.4411],
        [0.4076],
        [0.4505],
        [0.4555],
        [0.4330],
        [0.4514],
        [0.4184]], grad_fn=<SigmoidBackward0>)

In [17]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.0489, -0.1380,  0.1709, -0.3621, -0.0650]], requires_grad=True)

In [18]:
# show bias
model.linear.bias

Parameter containing:
tensor([-0.0519], requires_grad=True)

In [19]:
!pip install torchinfo

In [21]:
from torchinfo import summary


summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Neural net with hidden layer
5 inputs - 1 hidden layer(3 neuron) act=relu - 1 output layer (1 neuron) act = sigmoid

In [24]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3) #wx+b num_features = x(input) and 1 = output neuron
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):  #forward propagation

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [25]:
# create the simple dataset
features = torch.rand(10,5)

# create the model instance
model = Model(features.shape[1])

# call the model for forward pass
# model.forward(features)
model(features)

tensor([[0.3810],
        [0.3834],
        [0.3726],
        [0.3702],
        [0.3891],
        [0.3737],
        [0.3797],
        [0.3992],
        [0.3793],
        [0.3849]], grad_fn=<SigmoidBackward0>)

In [26]:
model.linear1

Linear(in_features=5, out_features=3, bias=True)

In [28]:
model.linear1.weight

Parameter containing:
tensor([[-0.2114,  0.4320,  0.0401,  0.4107, -0.0901],
        [-0.0446, -0.4339,  0.2965,  0.4167,  0.4362],
        [ 0.2501,  0.2701,  0.1679, -0.3565, -0.4144]], requires_grad=True)

In [30]:
model.linear2

Linear(in_features=3, out_features=1, bias=True)

In [31]:
model.linear2.weight

Parameter containing:
tensor([[-0.1126,  0.1436,  0.1838]], requires_grad=True)

In [32]:
model.linear1.bias

Parameter containing:
tensor([-0.0396, -0.4377, -0.2593], requires_grad=True)

In [33]:
model.linear2.bias

Parameter containing:
tensor([-0.4690], requires_grad=True)

In [34]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#using the sequential containers to improve the forward pass

In [36]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),

        nn.Linear(3,1),
        nn.Sigmoid()
    )


  def forward(self, features):  #forward propagation

    out = self.network(features)

    return out

In [37]:
# create the simple dataset
features = torch.rand(10,5)

# create the model instance
model = Model(features.shape[1])

# call the model for forward pass
# model.forward(features)
model(features)

tensor([[0.5195],
        [0.5272],
        [0.5243],
        [0.5189],
        [0.5378],
        [0.5381],
        [0.5464],
        [0.5419],
        [0.5368],
        [0.5316]], grad_fn=<SigmoidBackward0>)