Manual techniques of pytorch pipeline

In [41]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [42]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [43]:
df.shape

(569, 33)

In [44]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [45]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [46]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size=0.2)

#Scaling

In [47]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)  # Fit on training data and transform it
X_test = scaler.transform(X_test)        # Transform test data using the same scaler


In [48]:
X_train

array([[-0.66961626, -0.65608815, -0.54792013, ...,  1.0505285 ,
         4.60572887,  1.01437478],
       [-0.80132412,  1.8350987 , -0.83584103, ..., -1.41463008,
        -0.09464497, -0.71091501],
       [-0.51595709, -0.1910666 , -0.54712367, ..., -0.46841511,
         0.1206884 , -0.65829179],
       ...,
       [ 0.29624137, -0.49238158,  0.41619675, ...,  1.59215808,
         0.56260389,  1.87889907],
       [-0.39522489, -0.44730296, -0.38623841, ..., -0.49013981,
        -1.47824219, -0.72917204],
       [-0.56534754, -1.24922787, -0.6172123 , ..., -1.44900272,
        -0.98811774, -1.2747352 ]])

In [49]:
X_test

array([[-1.555626  , -1.48173865, -1.52199278, ..., -0.45799915,
         0.1206884 ,  1.11639938],
       [ 0.41422966, -0.0297326 ,  0.57150677, ...,  1.45228671,
         2.14867875,  1.1217691 ],
       [ 1.30600162, -0.10328192,  1.22062305, ...,  0.08779681,
        -0.10750069, -1.00410151],
       ...,
       [-1.04278853, -0.92181474, -1.04053169, ..., -1.06033886,
        -0.47067487, -0.07621456],
       [-0.48028622, -0.59202906, -0.53995551, ..., -1.31032174,
        -1.59233673, -1.20117009],
       [-0.01382088,  1.05927194,  0.00482428, ...,  0.91214512,
         2.91841519,  0.99289591]])

In [50]:
y_train

146    M
231    B
107    B
187    B
49     B
      ..
387    B
35     M
257    M
397    B
316    B
Name: diagnosis, Length: 455, dtype: object

# label Encoding

In [51]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [52]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,

# converting numpy array into the pytorch tensors

In [53]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [54]:
X_train_tensor.shape

torch.Size([455, 30])

#Defining the model

In [55]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn. Sigmoid()


  def forward(self , features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out


# important param

In [56]:
learning_rate = 0.1
epochs = 100

In [57]:
loss_function = nn.BCELoss()

# training pipeline

In [59]:
# Make sure tensors are float32
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()


# Create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)


# define loop
for epoch in range(epochs):

  # forward pass

  y_pred = model(X_train_tensor)


  # calculate loss
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))


  # clear grads
  optimizer.zero_grad()


  # backward pass
  loss.backward()

  # parameters update without tracking the gradient
  optimizer.step()


  # print loss in epochs
  print( f"Epochs: {epoch + 1},loss: {loss.item()}")


Epochs: 1,loss: 0.8120934367179871
Epochs: 2,loss: 0.5926620364189148
Epochs: 3,loss: 0.4789152443408966
Epochs: 4,loss: 0.4117777943611145
Epochs: 5,loss: 0.3667146563529968
Epochs: 6,loss: 0.3339550793170929
Epochs: 7,loss: 0.3088521361351013
Epochs: 8,loss: 0.28887858986854553
Epochs: 9,loss: 0.2725290358066559
Epochs: 10,loss: 0.25884607434272766
Epochs: 11,loss: 0.24718926846981049
Epochs: 12,loss: 0.23711274564266205
Epochs: 13,loss: 0.2282959371805191
Epochs: 14,loss: 0.22050173580646515
Epochs: 15,loss: 0.2135508507490158
Epochs: 16,loss: 0.20730476081371307
Epochs: 17,loss: 0.20165474712848663
Epochs: 18,loss: 0.19651392102241516
Epochs: 19,loss: 0.19181221723556519
Epochs: 20,loss: 0.18749214708805084
Epochs: 21,loss: 0.18350616097450256
Epochs: 22,loss: 0.17981456220149994
Epochs: 23,loss: 0.1763838827610016
Epochs: 24,loss: 0.17318573594093323
Epochs: 25,loss: 0.17019569873809814
Epochs: 26,loss: 0.16739289462566376
Epochs: 27,loss: 0.16475909948349
Epochs: 28,loss: 0.16227

In [60]:
model.linear

Linear(in_features=30, out_features=1, bias=True)

In [61]:
model.linear.weight

Parameter containing:
tensor([[ 0.2826,  0.3529,  0.5964,  0.3972,  0.0421,  0.3250,  0.1985,  0.3401,
          0.1740, -0.2157,  0.2972, -0.0202,  0.3338,  0.1680,  0.0582, -0.1605,
         -0.0387,  0.0972,  0.0164, -0.2025,  0.6598,  0.4588,  0.4074,  0.4002,
          0.2660,  0.1357,  0.3412,  0.4114,  0.2494,  0.0888]],
       requires_grad=True)

In [62]:
model.linear.bias

Parameter containing:
tensor([-0.2186], requires_grad=True)

# Evaluation

In [64]:
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()


with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

# print(y_pred)

Accuracy: 0.5443213582038879
