In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size=0.2)

#Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)  # Fit on training data and transform it
X_test = scaler.transform(X_test)        # Transform test data using the same scaler


In [8]:
X_train

array([[ 1.90347358,  2.32921688,  2.04599494, ...,  2.28165852,
         1.97902528,  2.18514349],
       [-0.72372749, -0.19564129, -0.75048033, ..., -0.47221693,
         0.51197155, -0.31398569],
       [ 0.47602766, -1.21525129,  0.43702925, ...,  0.35219165,
        -0.30268657, -0.7502454 ],
       ...,
       [ 0.23082223,  0.23015521,  0.18871644, ..., -0.18763568,
        -0.89486105, -1.01023856],
       [-0.08736101, -0.78715318, -0.13856661, ..., -1.22464852,
        -1.74799378, -0.8940128 ],
       [-0.77919063, -0.98739262, -0.76526085, ..., -0.7734315 ,
        -1.82828862, -0.55414886]])

In [9]:
X_test

array([[-0.9397418 ,  0.52245876, -0.9772558 , ..., -1.72546312,
        -0.74598102, -1.01409439],
       [-0.80838175, -0.0391323 , -0.83831887, ..., -0.67287543,
        -0.84300396, -0.98710357],
       [-0.34424289, -0.75723235, -0.33409183, ..., -0.19519629,
         1.07905389, -0.17352328],
       ...,
       [ 0.30671915,  2.43969381,  0.21363218, ..., -0.73124332,
         0.55044616, -1.24930007],
       [ 0.13157241, -1.20374327,  0.09327648, ..., -0.10900537,
        -0.49840525, -0.34317983],
       [ 0.85551226,  0.24166323,  0.7622008 , ..., -0.0681781 ,
         0.62070415, -1.08184684]])

In [10]:
y_train

567    M
463    B
133    B
344    B
167    M
      ..
208    B
543    B
495    B
442    B
183    B
Name: diagnosis, Length: 455, dtype: object

# label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,

# converting numpy array into the pytorch tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

#making the batch SGD :applying the Dataset and Dataloader

In [17]:
from torch.utils.data import Dataset, DataLoader

class CustomDataSet(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, index):

    return self.features[index], self.labels[index]




In [20]:
train_dataset = CustomDataSet(X_train_tensor, y_train_tensor)
test_dataset = CustomDataSet(X_test_tensor, y_test_tensor)

In [31]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [32]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn. Sigmoid()


  def forward(self , features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out


# Important param

In [33]:
learning_rate = 0.1
epochs = 100

In [34]:
# Create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

#define the loss function
loss_function = nn.BCELoss()


# training pipeline

In [35]:
# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass

    y_pred = model(batch_features)


    # calculate loss
    loss = loss_function(y_pred, batch_labels.view(-1,1))


    # clear grads
    optimizer.zero_grad()


    # backward pass
    loss.backward()

    # parameters update without tracking the gradient
    optimizer.step()


    # print loss in epochs
  print( f"Epochs: {epoch + 1},loss: {loss.item()}")


Epochs: 1,loss: 0.4427642822265625
Epochs: 2,loss: 0.11167781054973602
Epochs: 3,loss: 0.1591375321149826
Epochs: 4,loss: 0.19257350265979767
Epochs: 5,loss: 0.11178000271320343
Epochs: 6,loss: 0.04606785997748375
Epochs: 7,loss: 0.05302206799387932
Epochs: 8,loss: 0.017855847254395485
Epochs: 9,loss: 0.082456573843956
Epochs: 10,loss: 0.05971189960837364
Epochs: 11,loss: 0.08203203231096268
Epochs: 12,loss: 0.037126071751117706
Epochs: 13,loss: 0.11540462076663971
Epochs: 14,loss: 0.2193705290555954
Epochs: 15,loss: 0.11833669245243073
Epochs: 16,loss: 0.11337310820817947
Epochs: 17,loss: 0.019957033917307854
Epochs: 18,loss: 0.02067071758210659
Epochs: 19,loss: 0.06605799496173859
Epochs: 20,loss: 0.007375310640782118
Epochs: 21,loss: 0.39181143045425415
Epochs: 22,loss: 0.040633656084537506
Epochs: 23,loss: 0.009008434601128101
Epochs: 24,loss: 0.6252764463424683
Epochs: 25,loss: 0.0309735257178545
Epochs: 26,loss: 0.27768686413764954
Epochs: 27,loss: 0.041812244802713394
Epochs: 28

In [36]:
model.linear

Linear(in_features=30, out_features=1, bias=True)

In [37]:
model.linear.weight

Parameter containing:
tensor([[ 0.4285,  0.6350,  0.3088,  0.3846,  0.1786, -0.3726,  0.7769,  0.8062,
          0.0997, -0.4388,  0.8867, -0.1216,  0.7981,  1.0258, -0.1254, -0.4572,
         -0.1573,  0.1202, -0.5429, -0.5796,  0.9785,  1.0576,  0.8941,  0.8630,
          0.9357,  0.0917,  0.6231,  0.8621,  0.8218,  0.3385]],
       requires_grad=True)

In [38]:
model.linear.bias

Parameter containing:
tensor([-0.5180], requires_grad=True)

# Evaluation

In [40]:
# Model evaluation using the test_loader
model.eval()  #set the model to the evaluation mode
accuracy_list =[]

with torch.no_grad():
  for batch_features, batch_labels in test_loader:

    # forward pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float()

    # calculate the accuracy for the current batch
    batch_accuracy = (y_pred == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

# calculate the overall accuracy
overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f'Accuracy: {overall_accuracy: .4f}')

# print(y_pred)

Accuracy:  0.5193
