Manual techniques of pytorch pipeline

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [51]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [52]:
df.shape

(569, 33)

In [53]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [54]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size=0.2)

#Scaling

In [56]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)  # Fit on training data and transform it
X_test = scaler.transform(X_test)        # Transform test data using the same scaler


In [57]:
X_train

array([[-0.85978178,  0.77845017, -0.85057338, ..., -0.76110701,
         0.41029958, -0.20360936],
       [-0.69247194, -0.47974395, -0.71739416, ..., -0.06694478,
        -0.53479926, -0.70459845],
       [ 0.74408503,  0.24162068,  0.63610753, ..., -0.40864185,
         2.79758441, -0.4227586 ],
       ...,
       [-0.09534886, -0.81526238, -0.14585072, ..., -1.23141444,
        -1.66353539, -0.85837798],
       [-0.17611913, -1.55340293, -0.25773797, ..., -1.39854723,
        -1.0176387 , -1.18951302],
       [-0.44727647, -0.02919063, -0.4151316 , ..., -0.32856371,
        -1.2487684 , -0.65583908]])

In [58]:
X_test

array([[-0.68381798, -1.07888401, -0.64934333, ..., -0.13215993,
        -0.4841407 ,  0.78604502],
       [-0.77901151, -2.00635282, -0.77333778, ..., -0.3751243 ,
         0.16808832,  0.05947689],
       [-0.41266064,  1.1139686 , -0.38298489, ...,  0.86881685,
         0.74907872,  1.01698223],
       ...,
       [-0.476123  ,  0.16732731, -0.47733757, ..., -0.57729128,
        -0.35591121, -0.34720837],
       [-0.12996469, -0.96864224, -0.15002562, ..., -0.1351932 ,
         0.75541104,  0.65691307],
       [ 1.60659614,  0.59631159,  1.58798411, ...,  1.68628122,
         1.79707777, -0.26469252]])

In [59]:
y_train

551    B
187    B
489    M
422    B
506    B
      ..
349    B
225    B
442    B
308    B
355    B
Name: diagnosis, Length: 455, dtype: object

# label Encoding

In [61]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [62]:
y_train

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,

# converting numpy array into the pytorch tensors

In [64]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [66]:
X_train_tensor.shape

torch.Size([455, 30])

#Defining the model

In [79]:
class MySimpleNN():
  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True )

  def forward(self, X):
    z = torch.matmul(X , self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


# important param

In [95]:
learning_rate = 0.1
epochs = 25

# training pipeline

In [86]:
# create model
model = MySimpleNN(X_train_tensor)
# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)


  # calculate loss
  loss = model.loss_function(y_pred, y_train_tensor)


  # backward pass
  loss.backward()

  # parameters update without tracking the gradient
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()


  # print loss in epochs
  print( f"Epochs: {epoch + 1},loss: {loss.item()}")


Epochs: 1,loss: 3.4143120454473883
Epochs: 2,loss: 3.2776973657754076
Epochs: 3,loss: 3.140000203048686
Epochs: 4,loss: 2.996963559257398
Epochs: 5,loss: 2.8529660175909686
Epochs: 6,loss: 2.702684491146065
Epochs: 7,loss: 2.5511459954735796
Epochs: 8,loss: 2.396533824747551
Epochs: 9,loss: 2.2379567109608134
Epochs: 10,loss: 2.077189816953288
Epochs: 11,loss: 1.921035561010846
Epochs: 12,loss: 1.7682167156184367
Epochs: 13,loss: 1.6216314012885509
Epochs: 14,loss: 1.4840695279099492
Epochs: 15,loss: 1.3558894934062498
Epochs: 16,loss: 1.2393435597391311
Epochs: 17,loss: 1.1388527713564258
Epochs: 18,loss: 1.0551055441563073
Epochs: 19,loss: 0.9878723183609747
Epochs: 20,loss: 0.9357870840848783
Epochs: 21,loss: 0.8963721934718356
Epochs: 22,loss: 0.8665699525705024
Epochs: 23,loss: 0.8436015743697383
Epochs: 24,loss: 0.825402795047916
Epochs: 25,loss: 0.8105686542440279


In [87]:
model.weights

tensor([[-0.1018],
        [ 0.4989],
        [ 0.3043],
        [-0.2719],
        [ 0.4141],
        [-0.3895],
        [ 0.2959],
        [ 0.3726],
        [ 0.0463],
        [ 0.2018],
        [ 0.1555],
        [ 0.5074],
        [-0.2100],
        [-0.2858],
        [-0.2049],
        [ 0.5005],
        [-0.0145],
        [-0.1227],
        [ 0.2925],
        [-0.1256],
        [ 0.4436],
        [-0.2518],
        [ 0.0102],
        [-0.0540],
        [ 0.4645],
        [-0.2147],
        [-0.3331],
        [-0.4649],
        [ 0.0877],
        [-0.3142]], dtype=torch.float64, requires_grad=True)

In [88]:
model.bias

tensor([-0.1439], dtype=torch.float64, requires_grad=True)

# Evaluation

In [94]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

# print(y_pred)

Accuracy: 0.5183133482933044
