In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU : {torch.cuda.get_device_name()}")
else:
  print("GPU is not available, using CPU")

GPU is not available, using CPU


**Creating the Tensor**

In [4]:
a= torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
a


tensor([[0.0000e+00, 4.5439e+30, 6.6523e+22],
        [1.3225e-08, 3.2916e-09, 4.1951e-08]])

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.rand(2,3)

tensor([[0.0260, 0.9419, 0.8900],
        [0.9519, 0.4421, 0.7807]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [19]:
# others ways
print(torch.range(0,10,2))

tensor([ 0.,  2.,  4.,  6.,  8., 10.])


<ipython-input-19-5118756c1295>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(0,10,2))


In [20]:
print(torch.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


*shapes of tensor*

In [24]:
x = torch.tensor([[1,2,3],[2,3,1]])

In [25]:
x
x.shape

torch.Size([2, 3])

In [26]:
torch.empty_like(x)

tensor([[    132261040152640,     132261018082816,     132261040154496],
        [    132261040152704, 7526676553110265964,                  81]])

In [27]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Data types

In [29]:
x.dtype

torch.int64

In [30]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [32]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [2., 3., 1.]])

In [34]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# mahtematical operations on tensors

In [36]:
x

tensor([[1, 2, 3],
        [2, 3, 1]])

In [37]:
x + 2

tensor([[3, 4, 5],
        [4, 5, 3]])

In [38]:
x*2

tensor([[2, 4, 6],
        [4, 6, 2]])

In [39]:
x

tensor([[1, 2, 3],
        [2, 3, 1]])

In [40]:
(x * 100) % 2

tensor([[0, 0, 0],
        [0, 0, 0]])

In [42]:
b = torch.tensor([[1,2,2],[2,2,2]])

In [44]:
x

tensor([[1, 2, 3],
        [2, 3, 1]])

In [45]:
x+b

tensor([[2, 4, 5],
        [4, 5, 3]])

In [46]:
y = torch.tensor([1.3, 3.3, 4.5])

In [47]:
torch.ceil(y)

tensor([2., 4., 5.])

In [51]:
e = torch.randint(size=(2,3), low=0, high=10, dtype= torch.float32)
e

tensor([[4., 3., 8.],
        [7., 4., 6.]])

In [49]:
torch.sum(e)

tensor(25)

In [52]:
torch.mean(e)

tensor(5.3333)

In [53]:
torch.argmax(e)

tensor(2)

In [54]:
torch.argmin(e)

tensor(1)

In [63]:
x

tensor([[1, 2, 3],
        [2, 3, 1]])

In [70]:
y = torch.tensor([[1,2],
                 [2,2],
                 [3,3]])

In [67]:
y

tensor([[1, 2],
        [2, 2],
        [3, 3]])

In [71]:
result = torch.matmul(x, y)

In [72]:
print(result)

tensor([[14, 15],
        [11, 13]])


In [74]:
torch.transpose(y, 0,1)

tensor([[1, 2, 3],
        [2, 2, 3]])

In [75]:
a

tensor([[0.0000e+00, 4.5439e+30, 6.6523e+22],
        [1.3225e-08, 3.2916e-09, 4.1951e-08]])

In [76]:
b

tensor([[1, 2, 2],
        [2, 2, 2]])

In [77]:
x

tensor([[1, 2, 3],
        [2, 3, 1]])

In [78]:
b >x

tensor([[False, False, False],
        [False, False,  True]])

In [79]:
b>= x

tensor([[ True,  True, False],
        [ True, False,  True]])

In [80]:
b != x

tensor([[False, False,  True],
        [False,  True,  True]])

In [81]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986],
        [0.6931, 1.0986, 0.0000]])

In [82]:
torch.exp(a)

tensor([[1., inf, inf],
        [1., 1., 1.]])

In [91]:
k = torch.randint(low=0, high=10, size=(3, 2), dtype=torch.float32)

print(k)

tensor([[0., 1.],
        [9., 9.],
        [8., 0.]])


In [93]:
torch.softmax(k , dim=0)

tensor([[9.0212e-05, 3.3531e-04],
        [7.3099e-01, 9.9954e-01],
        [2.6892e-01, 1.2335e-04]])

In [94]:
torch.relu(k)

tensor([[0., 1.],
        [9., 9.],
        [8., 0.]])

inplace operation

In [95]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [96]:
print(m)
print(n)

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])
tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])


In [97]:
m.add_(n)

tensor([[1.4812, 0.9536, 0.9538],
        [1.3137, 0.5332, 0.2568]])

In [98]:
m

tensor([[1.4812, 0.9536, 0.9538],
        [1.3137, 0.5332, 0.2568]])

In [99]:
n

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])

In [100]:
m.relu_()

tensor([[1.4812, 0.9536, 0.9538],
        [1.3137, 0.5332, 0.2568]])

copying the tensors


In [103]:
a = torch.rand(2,3)
print(a)

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])


In [104]:
b = a

In [105]:
b

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

In [106]:
a[0][0] = 0

In [107]:
a

tensor([[0.0000, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

In [108]:
b

tensor([[0.0000, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

In [109]:
id(a)

132260977102480

In [110]:
id(b)

132260977102480

In [111]:
b = a.clone()

In [112]:
a

tensor([[0.0000, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

In [113]:
b

tensor([[0.0000, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

In [114]:
a[0][1] = 22

In [115]:
a

tensor([[ 0.0000, 22.0000,  0.4450],
        [ 0.7278,  0.4563,  0.3389]])

In [116]:
b

tensor([[0.0000, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

In [117]:
id(a)

132260977102480

In [118]:
id(b)

132260977456240

tensors operations on GPU

In [4]:
torch.cuda.is_available()

True

In [5]:
import torch

In [6]:
device = torch.device('cuda')

In [8]:
torch.rand((2,3), device =device)

tensor([[0.9415, 0.4813, 0.9438],
        [0.2672, 0.3952, 0.1873]], device='cuda:0')

In [9]:
# moving tensors in gpu
a = torch.rand(2,3)
a

tensor([[0.8217, 0.0165, 0.6499],
        [0.2239, 0.6671, 0.8666]])

In [11]:
b = a.to(device)

In [12]:
b

tensor([[0.8217, 0.0165, 0.6499],
        [0.2239, 0.6671, 0.8666]], device='cuda:0')

In [13]:
b+5

tensor([[5.8217, 5.0165, 5.6499],
        [5.2239, 5.6671, 5.8666]], device='cuda:0')

reshaping the tensors

In [14]:
a =torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [16]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
b = torch.rand(2,3,4)

In [18]:
b

tensor([[[0.0071, 0.2177, 0.6317, 0.0476],
         [0.6622, 0.9480, 0.3087, 0.8845],
         [0.4822, 0.3020, 0.0346, 0.3220]],

        [[0.7822, 0.3080, 0.2262, 0.8846],
         [0.3436, 0.4636, 0.2686, 0.7314],
         [0.8087, 0.0963, 0.0922, 0.8550]]])

In [20]:
b.permute(2 ,0, 1).shape

torch.Size([4, 2, 3])

In [24]:
c = torch.rand(226, 226 ,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [26]:
d = torch.rand(1,226,226,3)
d.squeeze(0).shape

torch.Size([226, 226, 3])

In [27]:
import numpy as np

In [28]:
a = torch.tensor([1,2,3])

In [29]:
a

tensor([1, 2, 3])

In [30]:
b = a.numpy()

In [31]:
b

array([1, 2, 3])

In [32]:
type(b)

numpy.ndarray

In [33]:
c = np.array([1,2,3])

In [34]:
c

array([1, 2, 3])

In [35]:
torch.from_numpy(c)

tensor([1, 2, 3])